apiVersion: v1
kind: ConfigMap
metadata:
  name: event-config
  namespace: eventhub
data:
  SECRET_KEY: event-service-secret
  DEBUG: "0"
  ALLOWED_HOSTS: "*"
  DB_HOST: postgres
  DB_PORT: "5432"
  DB_NAME: eventhub_events
  DB_USER: eventhub_event_user
