apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: eventhub
type: Opaque
stringData:
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: postgresadmin
  EVENT_DB_NAME: eventhub_events
  EVENT_DB_USER: eventhub_event_user
  EVENT_DB_PASSWORD: eventhub_event_pass
  USER_DB_NAME: eventhub_users
  USER_DB_USER: eventhub_user_user
  USER_DB_PASSWORD: eventhub_user_pass
