apiVersion: v1
kind: ConfigMap
metadata:
  name: user-config
  namespace: eventhub
data:
  SECRET_KEY: user-service-secret
  DEBUG: "0"
  ALLOWED_HOSTS: "*"
  DB_HOST: postgres
  DB_PORT: "5432"
  DB_NAME: eventhub_users
  DB_USER: eventhub_user_user
